# Generated by Django 3.2.3 on 2021-05-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='conversationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.conversation'),
        ),
    ]
